### ISSUE TITLE
Bootstrapping discovery?

### ISSUE THREAD

**Issue by ghenry** [kareldonk/QuantumGate#15]
Hi,

I'm working on https://github.com/SentryPeer/SentryPeer and wondered if you've been working on any WAN discovery or bootstrapping techniques?

Some chat here - https://github.com/zeromq/zyre/issues/701

Thanks,
Gavin.

**Comment by kareldonk** [comment]
Hi, peer discovery is planned for the future (this is basically what "DHT" is about in the readme file). It will support LAN and WAN. I looked at some of the information on the links you provided, and it seems like IPFS might be a solution for you in the mean time.

**Comment by ghenry** [comment]
Thanks Karel.
