### ISSUE TITLE
namespace "Implementation" is redundant

### ISSUE THREAD

**Issue by 0x4v0c4d0** [kareldonk/QuantumGate#17]
When I see the code, I already see that it is implementation of something. Namespace "Implementation" gives nothing to me. So I think this is redundant and should be removed.

Let's open the class view pane in MVSC and look into QuantumGateLib: there 3 namespaces in global scope: Algorithm, API and Implementation.

![image](https://user-images.githubusercontent.com/104268605/170819780-36a1f56d-07af-43c7-9314-4fa93ef75c8c.png)

So if the algorithms are separate, then what kind of implementation then inside of Implementation namespace. 

But even if you put the algorithms inside, then why. After all, it is already clear that inside the algorithms there is an implementation of algorithms. Why a separate implementation namespace is not clear

**Comment by kareldonk** [comment]
The reason namespace `Implementation` exists is because I want to communicate clearly what is internal to the library and what anyone using the library should not use directly in their own code.
