### ISSUE TITLE
Redundant Span and View

### ISSUE THREAD

**Issue by 0x4v0c4d0** [kareldonk/QuantumGate#18]
While reading code I decide that this:

```
  using BufferView = BufferSpanImpl<true>;
  using BufferSpan = BufferSpanImpl<false>;
```

is similar to this:

```
using BufferView = const Buffer&;
using BufferSpan = Buffer&;
```

If I not mistaken then I think Span and View is redundant and should be replaced as I noticed.

**Comment by kareldonk** [comment]
They are not similar. The `BufferView/Span` classes are lightweight views into other memory locations, usually `Buffer`s.
