### ISSUE TITLE
Unreferenced dependencies: pcg_random, monocypher

### ISSUE THREAD

**Issue by 0x4v0c4d0** [kareldonk/QuantumGate#19]
pcg_random library in QuantumGateLib\Common\Random.h - unreferenced dependency. Should add it into readme in dependency list.

monocypher library in Examples/QuantumGateExtenderHandshake/HandshakeExtender.cpp - unreferenced dependency. I see that is only example, but this is still should be noted in readme in dependency list section.

**Comment by kareldonk** [comment]
I do see PCG-Random listed as a dependency in the [readme](https://github.com/kareldonk/QuantumGate/blob/master/README.md).
