### ISSUE TITLE
A question on scaling and latency.

### ISSUE THREAD

**Issue by lonnietc** [kareldonk/QuantumGate#22]
Hello,

I have recently come across your QuantumGate project and it looks extremely interesting for possible use in some work that I am trying to get off the ground.

With that in mind, I am wondering if it has been tested for large scaling and, if so, then I was also wondering what the latency was at those scales?

My project involves many thousands (perhaps more) of concurrent P2P nodes across the Internet and I am looking for a base P2P framework that might be a good starting place to build for extremely huge number of connections.

Any thoughts?

**Comment by kareldonk** [comment]
It has not yet been tested for large scaling. Network communications with peers should be very fast, but right now you will have to handle peer lookup and DHT functionality yourself as it is not included yet. 
Not sure what you want to build, but it should be easy to prototype a small application and see if it will work for you.

**Comment by lonnietc** [comment]
Thanks for getting back to me on this.

I will have to experiment with it to see how to proceed on things. 

The first project is basically a type of P2P mutable storage system and perhaps an alternative to IPFS if it all goes well.  Based upon m reading of QG, it seems that this would be an extendable application written to run on top of QG.

As far as peer lookups and DHT, I will have to look into this more and see what might be needed. Do you have these things in the works for a future release?

On a side note, I was also thinking about a QG Extender that might offer VPN endpoints for users and perhaps WireGuard VPN might be a possibility but really have not thought about that yet since I would also be interested to see if QuantumGate could be make to run on Linux and OSX as well in the future.

**Comment by kareldonk** [comment]
> Based upon m reading of QG, it seems that this would be an extendable application written to run on top of QG.

That's correct, you would write an extender which is similar to a plugin.

> Do you have these things in the works for a future release?

Yes DHT will come but it will take some time.

>  I would also be interested to see if QuantumGate could be make to run on Linux and OSX as well in the future.

Linux definitely also planned for the future. 

For now I would say experiment with it. There are tutorials and some examples available in the Wiki. As for VPN, there is also a Socks5Extender example that can be used as a VPN. There are several articles in the Wiki talking about it. I sometimes use it myself like that.

**Comment by lonnietc** [comment]
Thanks and I will experiment with it more.

**Comment by lonnietc** [comment]
Just a quick question as I have been working mostly with Linux for a good while now, but is there a simple documentation on installing the Windows C++ dependencies on my Visual Studio 2022?

```
Dependencies
QuantumGate Core Library

Name	Version
OpenSSL	At least 3.0.0
PCG-Random	Latest.
zlib	At least 1.2.11
Zstandard	At least 1.5.1

QuantumGate Test Applications/Extenders

Name	Version
Monocypher	At least 3.1.2
JSON for Modern C++	At least 3.10.4
```

**Comment by kareldonk** [comment]
You can search the issues here for instructions for OpenSSL; I've answered questions about that in the past.

PCG-Random, Monocypher and JSON for Modern C++ are header only libraries so those should be easy to download and include.

zlib and zstandard also relatively easy: just download and open the Visual Studio solutions and build. You will have to change the build output names as described in the readme for QuantumGate.

If you don't want to build the libraries yourself, you can also just download the source code (for the header files) and then use the pre-built libraries from the QuantumGate release zip file.
