### ISSUE TITLE
QuantumGate Overview Question

### ISSUE THREAD

**Issue by lonnietc** [kareldonk/QuantumGate#23]
Hello,

I was reading the Overview documentation and it says:

```
.
.

...developers will be able to create extenders that can run on top of QuantumGate, which will provide various services on the network. In 2017 the decision was made to also allow developers in the short term to integrate QuantumGate directly into their own applications (instead of it running separately) and make it available as a library and API.
.
.
.

```

Is the design still the same in that QuantumGate is now a library that is compiled independently into each "extender" application?

It seems that the original idea was to have the QuantumGate P2P network and then have the extender applications compile to run on top of the P2P network. This would have actually been a great idea if QG was set up a VPN points using WireGuard or other such that the user would start up their P2P VPN node and then it would connect into the QuantumGate mesh network.

Then the users could easily build other extender applications (chat, email, etc.) that could just be started on the user nodes and communicate via the P2P VPN.

Now it seems that each application will effectively have its own QuantumGate P2P mesh that is independent from other QuantumGate P2P meshes that are running on a particular node.

Is this about correct?
Cheers,

**Comment by kareldonk** [comment]
> Is the design still the same in that QuantumGate is now a library that is compiled independently into each "extender" application?

Yes this is still the same. For example, all the current example and tutorial applications use the library independently.

> It seems that the original idea was to have the QuantumGate P2P network and then have the extender applications compile to run on top of the P2P network. This would have actually been a great idea if QG was set up a VPN points using WireGuard or other such that the user would start up their P2P VPN node and then it would connect into the QuantumGate mesh network.

Yes that is also still the goal when the DHT functionality gets added. There will be the main QuantumGate P2P network as described where everyone can plug into with their extenders.

But if people want to build their own customized applications and P2P infrastructure using the library, that will also be possible. For example, a company that wants to build an internal enterprise application using the QuantumGate network and security features.

**Comment by lonnietc** [comment]
Thanks for the clarification on this as I just wanted to make sure that I have the right picture of the work and goals.

I think that my initial project and goals are well aligned with QuantumGate and it should be exactly what I have been seeking for a long time.

Right now, I am working on getting all of the dependencies in place for my VS 2022 so start compiling the core code and subsequent examples.

Thanks again
