### ISSUE TITLE
Release Binaries Clarification, Please

### ISSUE THREAD

**Issue by lonnietc** [kareldonk/QuantumGate#24]
Hello and I hope that your day is going well.

I have just downloaded the QG Binaries in the Release section

```
https://github.com/kareldonk/QuantumGate/releases
```

In that file there is:

CmdMess.exe
QuantumGateConsoleExample.exe
QuantumGateExtenderExample.exe
QuantumGateExtenderHandShakeExample.exe
QuantumGateStartupExample.exe
TestApp64.exe

(plus some libraries).

After downloading, and not finding any available documentation for what each one does, I started up the "QuantumGateStartupExample" which seems to be the actual QG Mesh Network and then also started "CmdMess" which seems to be an interactive messaging system.

Please correct me if I am wrong about those 2 above.

What I am wondering is, if there is any documentation to show what is needed to be started for the QG core network and what runs on top of it.

Maybe some documentation or information on what each one does and how to use them would be very useful.

What I am doing now, is to evaluate QG since I think that it might be useful for a new project that I am working on which is strikingly different than the previous project that I was considering QG for use in that work.

Any clarification on these example projects and the core app needed to start up QG across multiple nodes would be greatly helpful.

Thanks in advance

**Comment by kareldonk** [comment]
Hi, all documentation can be found in [the wiki here on GitHub](https://github.com/kareldonk/QuantumGate/wiki), including for the example programs you mentioned. Take a look at the examples and tutorials pages there.

**Comment by lonnietc** [comment]
Hello,

I was able to find the documentation in the wiki and have been able to do some testing. Sorry about the extra post on this.

Also, I have a small confusion on the process.

For the QuantumGateExtenderExample.exe and QuantumGateExtenderHandshake.exe test files, I was actually able to start them up on the same local machine without needing to start up the QuantumGateStartupExample.exe.

Maybe, I do not have a clear picture of the QuantumGate process, but I thought that the actual QuantumGate mesh network needed to be started with the QuantumGateStartupExample.exe (which I thought was core QG network daemon) and then all extenders like the QuantumGateExtenderExample stalked through that core daemon. Did I miss something here?

After I learn more about QG, I will have a need to have a network mesh that could have many nodes coming online at any given time and I was trying to determine what is the core QG daemon that I need to run on each one when they boot up and want to join the mesh.

Once a node joins the network mesh, then I will have 3 extender applications on each node (shared file system, game server, and sandbox coordinator applications) that will be the extender applications that will utilize the QG network so that all of the nodes can communicate with each other through their extender servers as needed. 

That's the idea at least. 

Actually, after a LOT of evaluation of many different P2P and other possible solutions for my project, I have come to think that QuantumGate could be exactly what is needed, instead.  And, even though there still needs to be a lot of development and tuning to make it all work together, I think that this is the best available solution that I have found.

**Comment by lonnietc** [comment]
Maybe, if I now understand things then:

```
https://github.com/kareldonk/QuantumGate/wiki/Examples
```

1. QuantumGateStart(Example) is used to establish the core daemon for hops (relays) connecting and across the nodes themselves.

```
https://github.com/kareldonk/QuantumGate/wiki/Tutorials
```

2. QuantumGateExtenders will communicate across physical nodes via the daemon (above)

Also, I noticed that you mentioned that the DHT and Database functionality are not yet implemented and I would like to ask what they will provide for the core service. I know that the DHT will probably allow for quick lookups of each physical node, but right now, if you know the node's "Peer LUID" then you can communicate with that node. How will the DHT improve this?

For the Database, is this meant to be a P2P network database spread out across all peers?

Lastly, I was wondering if you have any type of file transfer extender example.  What I am seeking to probably come up with is a type of P2P file sharing example that will let all nodes on the network see all of the shared files in a collective directory structure so that they can get copies of files to be downloaded to their local space as needed. 

Still working out the ides for this, but I also started thinking about possibly using Dokan 

```
https://github.com/dokan-dev/dokany
and
http://dokan-dev.github.io/
```

So that maybe a type of QuantumGate  File Sharing extender could be mapped as a local drive sharing files through the core Quantum Gate daemon.

Any thoughts?

**Comment by lonnietc** [comment]
Any follow up on this?

**Comment by kareldonk** [comment]
> Maybe, I do not have a clear picture of the QuantumGate process, but I thought that the actual QuantumGate mesh network needed to be started with the QuantumGateStartupExample.exe (which I thought was core QG network daemon) and then all extenders like the QuantumGateExtenderExample stalked through that core daemon. Did I miss something here?

The examples are standalone examples; they don't work with or rely on each other. Each of them starts their own copy of the 'QG network daemon'. 

> After I learn more about QG, I will have a need to have a network mesh that could have many nodes coming online at any given time and I was trying to determine what is the core QG daemon that I need to run on each one when they boot up and want to join the mesh.

You can easily build that, but right now you will have to program the nodes yourself to connect to each other as the DHT functionality is not yet implemented.

> Once a node joins the network mesh, then I will have 3 extender applications on each node (shared file system, game server, and sandbox coordinator applications) that will be the extender applications that will utilize the QG network so that all of the nodes can communicate with each other through their extender servers as needed.

That's possible.

> Actually, after a LOT of evaluation of many different P2P and other possible solutions for my project, I have come to think that QuantumGate could be exactly what is needed, instead. And, even though there still needs to be a lot of development and tuning to make it all work together, I think that this is the best available solution that I have found.

When it comes to the core communications functionality, I think it will do a lot for you. And even more in the future. All you have to worry about is connecting your nodes and making your extenders.

**Comment by kareldonk** [comment]
> 1. QuantumGateStart(Example) is used to establish the core daemon for hops (relays) connecting and across the nodes themselves.

That example just shows you how to start the core deamon.

> 2. QuantumGateExtenders will communicate across physical nodes via the daemon (above)

Yes, you can load/add extenders to the core deamon which handle your custom functionality or services. Whenever nodes join that also have those extenders running, they can use the functionalities or services offered by those extenders among each other.

> Also, I noticed that you mentioned that the DHT and Database functionality are not yet implemented and I would like to ask what they will provide for the core service. I know that the DHT will probably allow for quick lookups of each physical node, but right now, if you know the node's "Peer LUID" then you can communicate with that node. How will the DHT improve this?

The DHT will automate a lot of the functionality for you that right now you would need to implement yourself, such as maintaining a database/list of nearby/favorite nodes, scanning for nearby nodes, building efficient paths across the network using reliable nodes etc. The DHT functionality will also make it possible to always have connections / network paths open for quick communication.
The core functionality in QuantumGate is built in a modular way, and the DHT functionality will also be a module that you can enable or disable based on your requirements. If you don't need the DHT you can disable it and perhaps build your own discovery functionality.
 
> For the Database, is this meant to be a P2P network database spread out across all peers?

Yes.

> Lastly, I was wondering if you have any type of file transfer extender example. What I am seeking to probably come up with is a type of P2P file sharing example that will let all nodes on the network see all of the shared files in a collective directory structure so that they can get copies of files to be downloaded to their local space as needed.

Yes, you can take a look at the [TestApp example](https://github.com/kareldonk/QuantumGate/wiki/Getting-started-with-the-QuantumGate-TestApp) which uses the TestExtender. The TestExtender has filetransfer functionality. Once you open the app, load the TestExtender via the **Extenders** menu and go to the **Test Extender** tab to try it out.

> So that maybe a type of QuantumGate File Sharing extender could be mapped as a local drive sharing files through the core Quantum Gate daemon.

That would be possible.
