### ISSUE TITLE
MultiChannel Support Question

### ISSUE THREAD

**Issue by lonnietc** [kareldonk/QuantumGate#25]
Hello,

I am working out the designs for a type of online gaming system for many users and will be using QuantumGate as the core network system.

To this end, the idea is to have QG Extenders integrated into the game servers. In this regard, there might, for example, be 5 servers in a cluster for Game-A and another cluster of machines, say 3 for example, for Game-B, and so on.

I am wondering if there would be any type of advantage to have all of the machines for Game-A, or Game-B and so one for that matter, clustered into their own QuantumGate network as extenders where a multicast message could be easily sent and received by just to machines on that QG network instance?

Or, is it better to work towards having specific but different extenders for the machine in each cluster group. For example, Game-A would all have similar extenders so that the Game-B machine does not get those messages, etc. for the Game-B and Game-C machines.

I think that my basic question is if it is better to have a single QuantumGate network with each cluster of machines having specific related extenders, or is it better to think about how to set up a QuantumGate network instance for tach cluster type (i.e. QG-A, QG-B, QG-C, etc.)

What would be more efficient?

Also, there "could" come a time when a machine on the Game-A cluster, might need to send a message to Game-B, or Game-C servers, and vice versa.

Mostly just playing with ideas to see what may, or may not, be efficient in working with Quantum Gate.
Thanks

**Comment by lonnietc** [comment]
Any follow up on this?

**Comment by kareldonk** [comment]
> I am wondering if there would be any type of advantage to have all of the machines for Game-A, or Game-B and so one for that matter, clustered into their own QuantumGate network as extenders where a multicast message could be easily sent and received by just to machines on that QG network instance?

The way QuantumGate works is that an extender can only send messages to peers that also have that extender installed and running on their own instance of the QuantumGate daemon. For example, a node A can connect to node B via QuantumGate, but on node B (which has extender E installed), the extender E will only get a notification that node A connected if node A also has extender E installed and running.
So you could have a single cluster of machines that can serve all games, and QuantumGate will make sure to route messages to the correct nodes and extenders.

> Or, is it better to work towards having specific but different extenders for the machine in each cluster group. For example, Game-A would all have similar extenders so that the Game-B machine does not get those messages, etc. for the Game-B and Game-C machines.

QuantumGate already does that for you so you can have a single cluster of machines serving all games.

> I think that my basic question is if it is better to have a single QuantumGate network with each cluster of machines having specific related extenders, or is it better to think about how to set up a QuantumGate network instance for tach cluster type (i.e. QG-A, QG-B, QG-C, etc.)

A single QuantumGate network should work fine. The server machines can run all the needed extenders and communications for all extenders will be kept separate by QuantumGate. Games A, B and C can all connect to the same cluster with their own extenders.
