### ISSUE TITLE
macOS and non-Intel archs support wanted

### ISSUE THREAD

**Issue by barracuda156** [kareldonk/QuantumGate#28]
Please consider supporting macOS and non-Intel archs.

**Comment by kareldonk** [comment]
Will do, but that might take a while.

**Comment by barracuda156** [comment]
@kareldonk Sounds good, thank you!

P. S. Please consider 32-bit and Big-endian arch along, if possible. (Testing on Linux/BSD is fine, I will handle macOS.)

**Comment by kareldonk** [comment]
32-bit is currently already supported on Windows. Big-endian support is also included but not tested as I don't have access to big-endian systems.

**Comment by barracuda156** [comment]
Awesome. I am primarily interested in macOS PowerPC (yeah, it is archaic), but as long as all three are supported on their own (32-bit, BE and macOS), that should work too. I will test once macOS gets support in principle.
